version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=libreria
      - POSTGRES_USER=iuser
      - POSTGRES_PASSWORD=user
    volumes:
      - ./postgres-volume:/var/postgresql
    ports:
      - 5432

  web:
    restart: always
    build: .
    ports:
      - 80:8080
    volumes:
      - .:/code
    depends_on:
      - db
    entrypoint: ["python", "application.py"]